encoding: utf-8
collections:
    athletic-performance-training:
        output: true
        defaults:
            scope:
                path: ""
                type: "athletic-performance-training"
            values:
                layout: "post"
    camps-clinics-workshops:
        output: true
        defaults:
            scope:
                path: ""
                type: "sub-index"
            values:
                layout: "post"
    getting-started:
        output: true
        defaults:
            scope:
                path: ""
                type: "getting-started"
            values:
                layout: "post"
    crossfit:
        output: true
        defaults:
            scope:
                path: ""
                type: "sub-index"
            values:
                layout: "post"
    coaches:
        output: true
        defaults:
            scope:
                path: ""
                type: "coaches"
            values:
                layout: "post"
    olympic-lifting:
        output: true
        defaults:
            scope:
                path: ""
                type: "olympic-lifting"
            values:
                layout: "post"
    hot-mammas:
        output: true
        defaults:
            scope:
                path: ""
                type: "hot-mammas"
            values:
                layout: "post"
    gallery:
        output: true
        defaults:
            scope:
                path: ""
                type: "gallery"
            values:
                layout: "gallery"        